<?php
/**
 * @file
 * A module implementing the Flux Slider Library.
 */

/**
 * Implements hook_help().
 */
function flux_slider_help($path, $arg) {
  if ($path == 'admin/help#flux_slider') {
    return t('Refer to the README.txt for further information regarding the use of the Flux Slider module.');
  }
}

/**
 * Implements hook_permission().
 */
function flux_slider_permission() {
  return array(
    'administer flux slider' => array(
      'title' => t('Administer Flux Slider'),
      'description' => t('Allows a user to configure Flux Slider'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function flux_slider_menu() {
  $items['admin/structure/flux-slider'] = array(
    'title' => 'Flux Slider',
    'description' => 'Configure slider content and options',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flux_slider_slide_configuration_form'),
    'access arguments' => array('administer flux slider'),
    'file' => 'flux_slider_slides.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/structure/flux-slider/slides'] = array(
    'title' => 'Flux Slider Slides',
    'description' => 'Configure slider content',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flux_slider_slide_configuration_form'),
    'access arguments' => array('administer flux slider'),
    'file' => 'flux_slider_slides.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/structure/flux-slider/options'] = array(
    'title' => 'Flux Slider Options',
    'description' => 'Configure slider options',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flux_slider_option_configuration_form'),
    'access arguments' => array('administer flux slider'),
    'file' => 'flux_slider_options.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function flux_slider_block_info() {
  $blocks = array();
  $blocks['flux_slider'] = array(
    'info' => t('Flux Slider'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Function to retrieve image paths from database.
 */
function flux_slider_get_images($path) {
  $images = array();
  $images = array(
    variable_get('first_img', $path . '/images/slider-img-1.jpg'),
    variable_get('second_img', $path . '/images/slider-img-2.jpg'),
    variable_get('third_img', $path . '/images/slider-img-3.jpg'),
    variable_get('fourth_img', $path . '/images/slider-img-4.jpg'),
  );
  return $images;
}

/**
 * Function to retrieve captions from database.
 */
function flux_slider_get_captions() {
  $captions = array();
  $captions = array(
    variable_get('first_capt', 'This is the first caption'),
    variable_get('second_capt', 'This is the second caption'),
    variable_get('third_capt', 'This is the third caption'),
    variable_get('fourth_capt', 'This is the fourth caption'),
  );
  return $captions;
}

/**
 * Function to retrieve alternative text for images from database.
 */
function flux_slider_get_alttext() {
  $alttext = array();
  $alttext = array(
    variable_get('first_alt', 'This is the first alt text'),
    variable_get('second_alt', 'This is the second alt text'),
    variable_get('third_alt', 'This is the third alt text'),
    variable_get('fourth_alt', 'This is the fourth alt text'),
  );
  return $alttext;
}

/**
 * Implements hook_block_view().
 */
function flux_slider_block_view($block_name = '') {
  if ($block_name == 'flux_slider') {
    // Check if the flux library has been installed.
    global $base_path;
    $flux_path = $_SERVER['DOCUMENT_ROOT'] . $base_path . '/sites/all/libraries/flux-slider';
    $installed = file_exists($flux_path . '/flux.min.js') || file_exists($flux_path . '/flux.js');

    if (!$installed) {
      drupal_set_message(t('The Flux Slider library is not installed, consult the modules README.txt for instructions.'), 'error');
    }
    else {
      // Set up the slider variables.
      $module_path = drupal_get_path('module', 'flux_slider');
      // Get the images.
      $images = flux_slider_get_images($module_path);
      $img_alt = flux_slider_get_alttext();
      // Get the captions.
      $captions = flux_slider_get_captions();
      $img_width = variable_get('trans_width');
      $img_height = variable_get('trans_height');
      $img_class = 'slider-images';
      $attributes = array($img_class);
      $all_images = '';
      $slide_count = 0;

      // Build the images.
      foreach ($images as $img_path) {
        $image = theme('image', array(
          'path' => $img_path,
          'alt' => $img_alt[$slide_count],
          'title' => $captions[$slide_count],
          'width' => $img_width,
          'height' => $img_height,
          'attributes' => $attributes,
        ));
        $all_images = $all_images . $image;
        $slide_count++;
      }
      $content = '<div id="slider">' . $all_images . '</div>';

      // Add the Flux javascript library.
      $lib_path = $base_path . "sites/all/libraries/flux-slider/flux.js";
      $js_path = $module_path . '/js/flux_slider.js';

      $options = array(
        'group' => JS_LIBRARY,
        'cache' => FALSE,
        'preprocess' => FALSE,
        'defer' => FALSE,
      );
      // Assign the settings for the JavaScript initialization routine.
      $flux_settings = array(
        'flux_autoplay' => variable_get('trans_autoplay'),
        'flux_transition' => variable_get('trans_type'),
        'flux_delay' => variable_get('trans_delay'),
        'flux_pagination' => variable_get('trans_pagination'),
        'flux_controls' => variable_get('trans_controls'),
        'flux_captions' => variable_get('trans_captions'),
        'flux_width' => variable_get('trans_width'),
        'flux_height' => variable_get('trans_height'),
      );
      // Add the Flux library.
      drupal_add_js($lib_path, $options);
      // Add the required JavaScript files and settings.
      drupal_add_js(array('flux_slider' => $flux_settings), 'setting');
      drupal_add_js($js_path, $flux_settings);

      // Build the block.
      $block = array(
        'content' => $content,
      );
      return $block;
    }
  }
}
