<?php
/**
 * @file
 * A module implementing the Flux Slider plugin.
 *
 * See http://www.joelambert.co.uk/flux/.
 */

/**
 * Implements hook_help().
 */
function flux_slider_help($path, $arg) {
  if ($path == 'admin/help#flux_slider') {
    return t('help description for flux slider.');
  }
}

/**
 * Implements hook_permission().
 */
function flux_slider_permission() {
  return array(
    'administer flux slider' => array(
      'title' => t('Administer Flux Slider'),
      'description' => t('Allows a user to confgigure Flux Slider'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function flux_slider_menu() {
  $items['admin/structure/flux-slider'] = array(
    'title' => 'Flux Slider',
    'description' => 'Configure slider content and options',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flux_slider_slide_configuration_form'),
    'access arguments' => array('administer flux slider'),
    'file' => 'flux_slider_slides.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/structure/flux-slider/slides'] = array(
    'title' => 'Flux Slider Slides',
    'description' => 'Configure slider content',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flux_slider_slide_configuration_form'),
    'access arguments' => array('administer flux slider'),
    'file' => 'flux_slider_slides.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/structure/flux-slider/options'] = array(
    'title' => 'Flux Slider Options',
    'description' => 'Configure slider options',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flux_slider_option_configuration_form'),
    'access arguments' => array('administer flux slider'),
    'file' => 'flux_slider_options.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function flux_slider_block_info() {
  $blocks = array();
  $blocks['flux_slider'] = array(
    'info' => t('Flux Slider'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Custom function to retrieve default images from module directory.
 */
function flux_slider_get_images() {
  $images = array();
  $images = array(
    variable_get('first_img'),
    variable_get('second_img'),
    variable_get('third_img'),
    variable_get('fourth_img'));
  return $images;
}

/**
 * Implements hook_block_view().
 */
function flux_slider_block_view($block_name = '') {
  if ($block_name == 'flux_slider') {
    // Set up the slider variables.
    $module_path = drupal_get_path('module', 'flux_slider');
    // Get the images.
    $images = flux_slider_get_images();
    $img_alt = 'default alternative text';
    $img_width = variable_get('trans_width');
    $img_height = variable_get('trans_height');
    $img_class = 'slider-images';
    $attributes = array($img_class);
    $all_images = '';

    foreach ($images as $img_path) {
      $image = theme('image', array(
        'path' => $img_path,
        'alt' => $img_alt,
        'width' => $img_width,
        'height' => $img_height,
        'attributes' => $attributes,
      ));
      $all_images = $all_images . $image;
    }
    $content = '<div id="slider">' . $all_images . '</div>';

    // Add the Flux javascript library.
    global $base_path;
    $lib_path = $base_path . "sites/all/libraries/flux-slider/flux.js";
    $js_path = $module_path . '/js/flux_slider.js';
    $css_path = $module_path . '/css/flux_slider.css';

    $options = array(
      'group' => JS_LIBRARY,
      'cache' => FALSE,
      'preprocess' => FALSE,
      'defer' => FALSE,
    );

    $flux_settings = array(
      'flux_autoplay' => variable_get('trans_autoplay'),
      'flux_transition' => variable_get('trans_type'),
      'flux_delay' => variable_get('trans_delay'),
      'flux_pagination' => variable_get('trans_pagination'),
      'flux_controls' => variable_get('trans_controls'),
      'flux_captions' => variable_get('trans_captions'),
      'flux_width' => variable_get('trans_width'),
      'flux_height' => variable_get('trans_height'),
    );

    drupal_add_js($lib_path, $options);
    drupal_add_js($js_path, $flux_settings);
    drupal_add_js(array('flux_slider' => $flux_settings), 'setting');
    drupal_add_css($css_path);

    // Build the block.
    $block = array(
      'content' => $content,
    );
    return $block;
  }
}
