<?php
/**
 * @file
 * A module implementing the Flux Slider Library.
 */

/**
 * Implements hook_help().
 */
function flux_slider_help($path, $arg) {
  if ($path == 'admin/help#flux_slider') {
    $help_text = '<h3>' . t('Flux Slider module description') . '</h3>';
    $help_text = '<p>' . t('Module for integrating the Flux Slider JavaScript library and controlling its configuration through an administration interface.') . '</p>';
    $help_text = '<p>' . t('The Flux Library must be installed at <em>/sites/all/libraries/flux-slider/flux.js</em>') . '</p>';
    $help_text = '<p>' . t('The module creates a block which can be positioned within the main blocks configuration page.') . '</p>';
    $help_text = '<p>' . t('Currently only supporting 4 images to be used within the slider along with 4 captions to appear with the transition. The images are currently served from the modules <em>/images/</em> directory but the image path can be changed to anything that is within the public files folders.') . '</p>';
    $help_text = '<p>' . t('Refer to the README.txt for further information regarding the use of the Flux Slider module.') . '</p>';

    return $help_text;
  }
}

/**
 * Implements hook_permission().
 */
function flux_slider_permission() {
  return array(
    'administer flux slider' => array(
      'title' => t('Administer Flux Slider'),
      'description' => t('Allows a user to configure Flux Slider'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function flux_slider_menu() {
  $items['admin/config/content/flux-slider'] = array(
    'title' => 'Flux Slider',
    'description' => 'Configure slider content and options',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flux_slider_slide_configuration_form'),
    'access arguments' => array('administer flux slider'),
    'file' => 'flux_slider_slides.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/content/flux-slider/slides'] = array(
    'title' => 'Flux-Slider slides',
    'description' => 'Configure slider content',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flux_slider_slide_configuration_form'),
    'access arguments' => array('administer flux slider'),
    'file' => 'flux_slider_slides.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/config/content/flux-slider/options'] = array(
    'title' => 'Flux-Slider options',
    'description' => 'Configure slider options',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flux_slider_option_configuration_form'),
    'access arguments' => array('administer flux slider'),
    'file' => 'flux_slider_options.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function flux_slider_block_info() {
  $blocks = array();
  $blocks['flux_slider'] = array(
    'info' => t('Flux Slider'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Function to retrieve image paths from database.
 */

function flux_slider_get_images() {
  $images = array();
  $image_fids = array(
    variable_get('flux_slider_first_img', ''),
    variable_get('flux_slider_second_img', ''),
    variable_get('flux_slider_third_img', ''),
    variable_get('flux_slider_fourth_img', ''),
  );
  foreach ($image_fids as $img_fid) {
      // Load image object
      $img_file = file_load($img_fid);
      //Get the uri
      $img_uri = $img_file->uri;
      // Get URL
      $img_url = file_create_url($img_uri);
      array_push($images, $img_url);
  }
  return $images;
}

/**
 * Implements hook_block_view().
 */
function flux_slider_block_view($block_name = '') {
  if ($block_name == 'flux_slider') {
    // Check if the flux library has been installed.
    $flux_path = libraries_get_path('flux-slider');
    $installed_full = file_exists($flux_path . '/flux.js');
    $installed_min = file_exists($flux_path . '/flux.min.js');
    if ((!$installed_min) && (!$installed_full)) {
      drupal_set_message(t('The Flux Slider library is not installed, consult the modules README.txt for instructions.'), 'error');
    }
    else {
      // Set up the slider variables.
      $module_path = drupal_get_path('module', 'flux_slider');

      $image_paths = flux_slider_get_images();

      $slider_settings = variable_get('flux_slider_settings');

      $img_alt = variable_get('flux_slider_alts');
      $captions = variable_get('flux_slider_captions');

      $img_width = variable_get('flux_slider_trans_width');
      $img_height = variable_get('flux_slider_trans_height');

      $img_class = 'slider-images';
      $attributes = array($img_class);
      $all_images = '';
      $slide_count = 0;

      // Build the images.
      foreach ($image_paths as $img_path) {
        $image = theme('image', array(
          'path' => $img_path,
          'alt' => $img_alt[$slide_count],
          'title' => $captions[$slide_count],
          'width' => $img_width,
          'height' => $img_height,
          'attributes' => $attributes,
        ));
        $all_images = $all_images . $image;
        $slide_count++;
      }
      
      $content = '<div id="slider">' . $all_images . '</div>';

      // Add the Flux javascript library.
      if($installed_min) {
        $lib_path = $flux_path . '/flux.min.js';
      }
      else if ($installed_full) {
        $lib_path = $flux_path . '/flux.js';
      }

      $js_path = $module_path . '/js/flux_slider.js';
      $css_path = $module_path . '/css/flux_slider.css';

      $options = array(
        'group' => JS_LIBRARY,
        'cache' => FALSE,
        'preprocess' => FALSE,
        'defer' => FALSE,
      );

      // Assign the settings for the JavaScript initialization routine.
      $flux_settings = array(
        'flux_autoplay' => $slider_settings[1],
        'flux_transition' => $slider_settings[0],
        'flux_delay' => $slider_settings[2],
        'flux_pagination' => $slider_settings[3],
        'flux_controls' => $slider_settings[4],
        'flux_captions' => $slider_settings[5],
        'flux_width' => $slider_settings[6],
        'flux_height' => $slider_settings[7],
      );
      // Add the Flux library.
      drupal_add_js($lib_path, $options);
      // Add the required JavaScript files and settings.
      drupal_add_js(array('flux_slider' => $flux_settings), 'setting');
      drupal_add_js($js_path, $flux_settings);

      // Add frontend styles
      drupal_add_css($css_path);

      // Build the block.
      $block = array(
        'content' => $content,
      );
      return $block;
    }
  }
}
